### ISSUE TITLE
Module 4. 1.1 Bias-variance trade-off

### ISSUE THREAD

**Issue by AlexYash** [MicrosoftLearning/Deep-Learning-Explained#1]
![Annotation 2019-09-16 194016](https://user-images.githubusercontent.com/45464862/64976473-09b6c380-d8ba-11e9-9cd2-93cb97a1456b.jpg)

Looks like a typo.

**Comment by StephenElston** [comment]
This is definitely a typo. Thanks for pointing this out. 

However, I am not sure which notebook you are looking in.

**Comment by AlexYash** [comment]
Hi, this one - https://github.com/MicrosoftLearning/Deep-Learning-Explained/blob/master/Module4/IntroToRegularization.ipynb

**Comment by StephenElston** [comment]
Ah ha!!! I have fixed the error. Thank you again for bringing this to my attention.
