### ISSUE TITLE
Module 5. 1.1 Local convergence of optimization algorithms

### ISSUE THREAD

**Issue by AlexYash** [MicrosoftLearning/Deep-Learning-Explained#2]
Hello,
Should it be W^(l) instead of W^(i) in the loss function equation?

![Annotation 2019-09-20 175052](https://user-images.githubusercontent.com/45464862/65336898-d634ab80-dbcf-11e9-98ee-b471c34aa126.jpg)

The notebook is here - https://github.com/MicrosoftLearning/Deep-Learning-Explained/blob/master/Module5/OptimizatonForDeepNetworks.ipynb

**Comment by StephenElston** [comment]
Thank you for noticing this problem Alex. I have made a correction.
